<?php

/**
 * @file
 * Provides Schema mapping for Ministry of Finance of the Czech Republic for Open Data Schema Mapper module for the Czech national open data catalogue.
 */

/**
 * Implements hook_open_data_schema_map_endpoints_alter().
 */
function open_data_schema_mfcr_open_data_schema_map_endpoints_alter(&$records) {
  $records[] = 'mfcr_site_read';
}

/**
 * Implements hook_open_data_schema_map_load().
 */
function open_data_schema_mfcr_open_data_schema_map_load($machine_name) {
  if ($machine_name == 'mfcr_site_read') {
    $record = new stdClass();
    $record->name = 'MFCR Site Read';
    $record->enabled = TRUE;
    $record->api_schema = 'mfcr_no_schema';
    $record->entity = '';
    $record->bundle = '';
    $record->arguments = array();
    $record->machine_name = 'mfcr_site_read';
    $record->endpoint = 'api/3/action/site_read';
    $record->callback = 'open_data_schema_mfcr_site_read_callback';
    return $record;
  }
}

/**
 * Site read callback.
 */
function open_data_schema_mfcr_site_read_callback() {
  return TRUE;
}

/**
 * Implements hook_open_data_schema().
 */
function open_data_schema_mfcr_open_data_schema() {
  $schemas_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'open_data_schema_mfcr') . '/data/';
  return array(
    array(
      'short_name' => 'mfcr_dataset',
      'title' => 'MFCR Dataset',
      'schema_file' => $schemas_path . 'mfcr_dataset_schema.json',
      'description' => t('Schéma datové sady katalogu otevøených dat MFÈR.'),
    ),
    array(
      'short_name' => 'mfcr_group',
      'title' => 'MFCR Group',
      'schema_file' => $schemas_path . 'mfcr_group_schema.json',
      'description' => t('Schéma skupiny datových sad katalogu otevøených dat MFÈR.'),
    ),
    array(
      'short_name' => 'mfcr_resource',
      'title' => 'MFCR Resource',
      'schema_file' => $schemas_path . 'mfcr_resource_schema.json',
      'description' => t('Schéma datového soubory katalogu otevøených dat MFÈR.'),
    )
  );
}

/**
 * Implements hook_open_data_schema_map_results_alter().
 */
function open_data_schema_mfcr_open_data_schema_map_results_alter(&$result, $machine_name, $api_schema) {
  $mfcr_schemas = array(
    'mfcr_dataset',
    'mfcr_group',
    'mfcr_resource',
    'mfcr_no_schema',
  );
  if (in_array($api_schema, $mfcr_schemas)) {
  
    /* 
    * In case of mfcr_dataset, ODSM returns an array of results meeting the criteria,
    * therefore when accessing package_show, we get array with one item instead of
    * just the item itself. This solves the problem.
    */          
    if(is_array($result) && count($result) === 1 && isset($result[0])) $result = $result[0];
    
    // CKAN expects results wrapped in help, success, result.
    $response = array(
      'help' => '',
      'success' => TRUE,
      'result' => $result,
    );
    
    /*
    * If there is an error we return it
    */         
    if (isset($result['error'])) {
      $response['success'] = FALSE;
      $response['error'] = $result['error'];
      unset($response['result']);
    }
    
    /*
    * Since this hook insn't wrapped in the try catch stament
    * we need to manage not found error by hand
    */
    if (!isset($result['error']) && $response['result'] === NULL) {
      $error = array(
        '__type' => 'Not Found Error',
        'message' => 'Not Found',
      );
      $response['error'] = $error;
      unset($response['result']);
      drupal_add_http_header('Status', '404 Not Found');
    }
    $result = $response;
  }
}
   
?>